import type { PrototypeSet } from "./types"

// Generated by scripts/update-part-color-prototypes.mjs.
// Contains aggregate prototype data only; no private row, crop, or manual ids.
export const RUNTIME_COLOR_PROTOTYPES: PrototypeSet = {
  "prototypes": [
    {
      "expectedName": "Black",
      "family": "neutral",
      "id": "prototype-black-001",
      "lab": {
        "a": -0.025188,
        "b": -5.347917,
        "l": 4.169273
      },
      "rgb": {
        "b": 23,
        "g": 15,
        "r": 9
      },
      "support": 27
    },
    {
      "expectedName": "Dark Azure",
      "family": "cool",
      "id": "prototype-dark-azure-002",
      "lab": {
        "a": -8.453011,
        "b": -43.674306,
        "l": 59.26533
      },
      "rgb": {
        "b": 219,
        "g": 151,
        "r": 11
      },
      "support": 11
    },
    {
      "expectedName": "Dark Bluish Gray",
      "family": "neutral",
      "id": "prototype-dark-bluish-gray-003",
      "lab": {
        "a": -0.124761,
        "b": -0.534336,
        "l": 3.280288
      },
      "rgb": {
        "b": 13,
        "g": 12,
        "r": 11
      },
      "support": 5
    },
    {
      "expectedName": "Dark Bluish Gray",
      "family": "neutral",
      "id": "prototype-dark-bluish-gray-029",
      "lab": {
        "a": -1.141258,
        "b": -1.706183,
        "l": 37.119119
      },
      "rgb": {
        "b": 90,
        "g": 88,
        "r": 84
      },
      "support": 16
    },
    {
      "expectedName": "Dark Bluish Gray",
      "family": "neutral",
      "id": "prototype-dark-bluish-gray-004",
      "lab": {
        "a": -1.608343,
        "b": 1.992828,
        "l": 42.08576
      },
      "rgb": {
        "b": 96,
        "g": 100,
        "r": 98
      },
      "support": 109
    },
    {
      "expectedName": "Dark Bluish Gray",
      "family": "neutral",
      "id": "prototype-dark-bluish-gray-005",
      "lab": {
        "a": -1.944844,
        "b": 3.018335,
        "l": 50.889105
      },
      "rgb": {
        "b": 116,
        "g": 122,
        "r": 120
      },
      "support": 25
    },
    {
      "expectedName": "Dark Brown",
      "family": "tan-gold",
      "id": "prototype-dark-brown-006",
      "lab": {
        "a": 11.492379,
        "b": 21.791668,
        "l": 15.197405
      },
      "rgb": {
        "b": 2,
        "g": 31,
        "r": 60
      },
      "support": 3
    },
    {
      "expectedName": "Dark Orange",
      "family": "tan-gold",
      "id": "prototype-dark-orange-007",
      "lab": {
        "a": 32.914281,
        "b": 56.663683,
        "l": 48.962165
      },
      "rgb": {
        "b": 5,
        "g": 91,
        "r": 183
      },
      "support": 11
    },
    {
      "expectedName": "Dark Red",
      "family": "warm",
      "id": "prototype-dark-red-008",
      "lab": {
        "a": 41.373725,
        "b": 29.315283,
        "l": 20.601111
      },
      "rgb": {
        "b": 5,
        "g": 3,
        "r": 106
      },
      "support": 3
    },
    {
      "expectedName": "Dark Tan",
      "family": "tan-gold",
      "id": "prototype-dark-tan-009",
      "lab": {
        "a": 0.065809,
        "b": 14.363874,
        "l": 57.829525
      },
      "rgb": {
        "b": 114,
        "g": 138,
        "r": 149
      },
      "support": 12
    },
    {
      "expectedName": "Green",
      "family": "cool",
      "id": "prototype-green-011",
      "lab": {
        "a": -26.090067,
        "b": 17.867837,
        "l": 27.383844
      },
      "rgb": {
        "b": 36,
        "g": 74,
        "r": 25
      },
      "support": 4
    },
    {
      "expectedName": "Green",
      "family": "cool",
      "id": "prototype-green-010",
      "lab": {
        "a": -15.685259,
        "b": 11.601601,
        "l": 19.130198
      },
      "rgb": {
        "b": 29,
        "g": 52,
        "r": 27
      },
      "support": 9
    },
    {
      "expectedName": "Green",
      "family": "cool",
      "id": "prototype-green-012",
      "lab": {
        "a": -39.177268,
        "b": 25.98014,
        "l": 42.456817
      },
      "rgb": {
        "b": 55,
        "g": 115,
        "r": 29
      },
      "support": 12
    },
    {
      "expectedName": "Green",
      "family": "cool",
      "id": "prototype-green-030",
      "lab": {
        "a": -19.484634,
        "b": 13.993437,
        "l": 24.806136
      },
      "rgb": {
        "b": 37,
        "g": 66,
        "r": 33
      },
      "support": 5
    },
    {
      "expectedName": "Light Bluish Gray",
      "family": "neutral",
      "id": "prototype-light-bluish-gray-013",
      "lab": {
        "a": -0.405267,
        "b": -1.720216,
        "l": 9.130681
      },
      "rgb": {
        "b": 28,
        "g": 26,
        "r": 24
      },
      "support": 9
    },
    {
      "expectedName": "Light Bluish Gray",
      "family": "neutral",
      "id": "prototype-light-bluish-gray-014",
      "lab": {
        "a": -0.705507,
        "b": -1.464024,
        "l": 54.959666
      },
      "rgb": {
        "b": 134,
        "g": 132,
        "r": 129
      },
      "support": 20
    },
    {
      "expectedName": "Light Bluish Gray",
      "family": "neutral",
      "id": "prototype-light-bluish-gray-031",
      "lab": {
        "a": -2.365032,
        "b": 0.93589,
        "l": 65.769016
      },
      "rgb": {
        "b": 158,
        "g": 161,
        "r": 156
      },
      "support": 55
    },
    {
      "expectedName": "Light Bluish Gray",
      "family": "neutral",
      "id": "prototype-light-bluish-gray-015",
      "lab": {
        "a": -0.638049,
        "b": -2.557938,
        "l": 67.914278
      },
      "rgb": {
        "b": 170,
        "g": 166,
        "r": 162
      },
      "support": 375
    },
    {
      "expectedName": "Medium Nougat",
      "family": "tan-gold",
      "id": "prototype-medium-nougat-016",
      "lab": {
        "a": 19.23732,
        "b": 48.61476,
        "l": 76.293503
      },
      "rgb": {
        "b": 98,
        "g": 173,
        "r": 246
      },
      "support": 12
    },
    {
      "expectedName": "Pearl Gold",
      "family": "tan-gold",
      "id": "prototype-pearl-gold-035",
      "lab": {
        "a": 0.784451,
        "b": 43.189423,
        "l": 45.736752
      },
      "rgb": {
        "b": 31,
        "g": 106,
        "r": 129
      },
      "support": 4
    },
    {
      "expectedName": "Pearl Gold",
      "family": "tan-gold",
      "id": "prototype-pearl-gold-028",
      "lab": {
        "a": 5.206992,
        "b": 59.948905,
        "l": 62.340042
      },
      "rgb": {
        "b": 33,
        "g": 145,
        "r": 186
      },
      "support": 4
    },
    {
      "expectedName": "Pearl Gold",
      "family": "tan-gold",
      "id": "prototype-pearl-gold-036",
      "lab": {
        "a": 9.987692,
        "b": 62.505747,
        "l": 66.196564
      },
      "rgb": {
        "b": 38,
        "g": 152,
        "r": 205
      },
      "support": 12
    },
    {
      "expectedName": "Red",
      "family": "warm",
      "id": "prototype-red-017",
      "lab": {
        "a": 67.185436,
        "b": 55.853072,
        "l": 44.244225
      },
      "rgb": {
        "b": 7,
        "g": 18,
        "r": 209
      },
      "support": 7
    },
    {
      "expectedName": "Reddish Brown",
      "family": "neutral",
      "id": "prototype-reddish-brown-018",
      "lab": {
        "a": 0.513063,
        "b": 1.035681,
        "l": 2.330237
      },
      "rgb": {
        "b": 6,
        "g": 8,
        "r": 11
      },
      "support": 22
    },
    {
      "expectedName": "Reddish Brown",
      "family": "tan-gold",
      "id": "prototype-reddish-brown-019",
      "lab": {
        "a": 10.253498,
        "b": 13.338133,
        "l": 13.201181
      },
      "rgb": {
        "b": 15,
        "g": 28,
        "r": 52
      },
      "support": 57
    },
    {
      "expectedName": "Reddish Brown",
      "family": "tan-gold",
      "id": "prototype-reddish-brown-020",
      "lab": {
        "a": 20.966231,
        "b": 25.567895,
        "l": 21.324319
      },
      "rgb": {
        "b": 13,
        "g": 37,
        "r": 86
      },
      "support": 45
    },
    {
      "expectedName": "Tan",
      "family": "tan-gold",
      "id": "prototype-tan-021",
      "lab": {
        "a": 0.365537,
        "b": 26.854104,
        "l": 88.803339
      },
      "rgb": {
        "b": 172,
        "g": 221,
        "r": 243
      },
      "support": 9
    },
    {
      "expectedName": "Teal",
      "family": "cool",
      "id": "prototype-teal-022",
      "lab": {
        "a": -24.847682,
        "b": -15.516695,
        "l": 49.814517
      },
      "rgb": {
        "b": 144,
        "g": 131,
        "r": 3
      },
      "support": 3
    },
    {
      "expectedName": "Trans-Light Blue",
      "family": "cool",
      "id": "prototype-trans-light-blue-032",
      "lab": {
        "a": -7.084486,
        "b": -8.268766,
        "l": 66.064835
      },
      "rgb": {
        "b": 175,
        "g": 165,
        "r": 138
      },
      "support": 4
    },
    {
      "expectedName": "Trans-Green",
      "family": "cool",
      "id": "prototype-trans-green-038",
      "lab": {
        "a": -23.629799,
        "b": 11.151498,
        "l": 49.473883
      },
      "rgb": {
        "b": 98,
        "g": 128,
        "r": 79
      },
      "support": 5
    },
    {
      "expectedName": "Trans-Orange",
      "family": "tan-gold",
      "id": "prototype-trans-orange-023",
      "lab": {
        "a": 8.846388,
        "b": 37.388531,
        "l": 74.249371
      },
      "rgb": {
        "b": 114,
        "g": 175,
        "r": 220
      },
      "support": 3
    },
    {
      "expectedName": "Trans-Orange",
      "family": "tan-gold",
      "id": "prototype-trans-orange-039",
      "lab": {
        "a": 8.585931,
        "b": 22.678447,
        "l": 25.566978
      },
      "rgb": {
        "b": 26,
        "g": 55,
        "r": 82
      },
      "support": 4
    },
    {
      "expectedName": "Trans-Yellow",
      "family": "tan-gold",
      "id": "prototype-trans-yellow-041",
      "lab": {
        "a": -4.036485,
        "b": 40.509094,
        "l": 64.288634
      },
      "rgb": {
        "b": 82,
        "g": 156,
        "r": 172
      },
      "support": 4
    },
    {
      "expectedName": "White",
      "family": "neutral",
      "id": "prototype-white-024",
      "lab": {
        "a": 0.332134,
        "b": 0.117028,
        "l": 4.040833
      },
      "rgb": {
        "b": 14,
        "g": 14,
        "r": 15
      },
      "support": 3
    },
    {
      "expectedName": "White",
      "family": "neutral",
      "id": "prototype-white-025",
      "lab": {
        "a": 0.189665,
        "b": -0.514679,
        "l": 68.892036
      },
      "rgb": {
        "b": 169,
        "g": 168,
        "r": 168
      },
      "support": 6
    },
    {
      "expectedName": "White",
      "family": "neutral",
      "id": "prototype-white-026",
      "lab": {
        "a": -0.000016,
        "b": 0.000007,
        "l": 98.618143
      },
      "rgb": {
        "b": 251,
        "g": 251,
        "r": 251
      },
      "support": 75
    },
    {
      "expectedName": "Yellow",
      "family": "tan-gold",
      "id": "prototype-yellow-027",
      "lab": {
        "a": -4.782258,
        "b": 78.633859,
        "l": 88.041592
      },
      "rgb": {
        "b": 54,
        "g": 220,
        "r": 252
      },
      "support": 5
    }
  ]
}
